FROM apache/airflow:3.3.0-python3.12

USER root

RUN apt-get update \
    && apt-get install --yes --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow==3.3.0" \
    "pyspark==4.2.0"

COPY --chown=airflow:root airflow/dags /opt/airflow/dags
COPY --chown=airflow:root pipelines /opt/airflow/pipelines
